### ISSUE TITLE
Feature Request: pip install eerepr

### ISSUE THREAD

**Issue by intotecho** [google/earthengine-jupyter#24]
[eerepr](https://twitter.com/aazuspan/status/1591229797707173889?s=46&t=paSDn7DoaVjSnhZaORQAGg)

**Comment by tylere** [comment]
Please provide more context for this request. Why is it relevant?

**Comment by intotecho** [comment]
[eerepr](https://github.com/aazuspan/eerepr) provides the ability to Interactively explore any Earth Engine object by printing it in a Jupyter notebook, just like you can in the javascript code editor.

**Comment by tylere** [comment]
If you want the functionality `eerepr` provides, why not just install and import the library?

**Comment by intotecho** [comment]
Yes, that will work. I mixed up this project with the container to pre-install the libraries. 
I like the way this project  pulls in ipyleaflet when pip installs ee_jupyter to minimise the pip interactions.
