### ISSUE TITLE
Turn off EE layer in leaflet doesn't make EE layer disappear

### ISSUE THREAD

**Issue by intotecho** [google/earthengine-jupyter#25]
![image](https://user-images.githubusercontent.com/659672/202431369-cc88bef8-a666-43b6-9a7c-aba38e6a4586.png)

**Comment by tylere** [comment]
Please include a link to a Colab script or code repository, so that the issue can be reproduced.

**Comment by intotecho** [comment]
Sorry, I can't reproduce it now. It was probably a stalled notebook. Closing.
